stages:
  # Data Ingestion Stage
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - notebooks/data_processing.csv
      - params.yaml
    outs:
      - datas/raw/train.csv
      - datas/raw/test.csv
    params:
      - data_ingestion.test_size

  # Data Preprocessing Stage
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - datas/raw/train.csv
      - datas/raw/test.csv
    outs:
      - datas/interim/train_processed.csv
      - datas/interim/test_processed.csv

  # Feature Engineering Stage
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - datas/interim/train_processed.csv
      - datas/interim/test_processed.csv
      - params.yaml
    outs:
      - datas/processed/train_features.csv
      - datas/processed/test_features.csv
      - models/feature_scaler.pkl
    params:
      - feature_engineering.max_features

  # Model Training Stage
  model_training:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - src/model/mlflow_utils.py
      - datas/processed/train_features.csv
      - config.yaml
      - mlflow_config.yaml
    outs:
      - models/rnn_model.h5
    params:
      - input_dim
      - epochs
      - batch_size
      - units
      - dropout
      - activation
      - rnn_type
      - lr
      - clipnorm
      - l2
      - patience

  # Model Evaluation Stage
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - src/model/mlflow_utils.py
      - models/rnn_model.h5
      - datas/processed/test_features.csv
      - mlflow_config.yaml
    metrics:
      - reports/metrics.json:
          cache: false
    outs:
      - reports/figures/

  # Model Prediction Stage
  model_prediction:
    cmd: python src/model/predict_model.py
    deps:
      - src/model/predict_model.py
      - models/rnn_model.h5
      - datas/processed/test_features.csv
    outs:
      - reports/predictions.csv

  # Model Registration Stage
  model_registration:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - src/model/mlflow_utils.py
      - src/model/model_registry.py
      - models/rnn_model.h5
      - reports/metrics.json
      - mlflow_config.yaml
    outs:
      - mlruns/:
          persist: true
    metrics:
      - reports/experiment_info.json:
          cache: false
          persist: true

  # Model Production Management
  model_production:
    cmd: python src/model/production_model_manager.py
    deps:
      - src/model/production_model_manager.py
      - src/model/mlflow_utils.py
      - src/model/model_registry.py
      - models/rnn_model.h5
      - models/feature_scaler.pkl
      - mlflow_config.yaml
      - reports/metrics.json
    outs:
      - models/production_model.h5
  # Data Visualization Stage
  data_visualization:
    cmd: python src/visualization/visualize.py
    deps:
      - src/visualization/visualize.py
      - datas/processed/train_features.csv
      - datas/processed/test_features.csv

  # FastAPI Model Testing
  api_model_testing:
    cmd: python fast_api/load_model_test.py
    deps:
      - fast_api/load_model_test.py
      - models/rnn_model.h5
      - models/feature_scaler.pkl
    outs:
      - logs/api_test.log

  # Documentation Generation
  documentation:
    cmd: cd docs && make.bat html
    deps:
      - docs/conf.py
      - docs/index.rst
      - docs/getting-started.rst
      - docs/commands.rst
    outs:
      - docs/_build/html/